version: '3.4'

services:
  postgres:
    container_name: security
    image: library/postgres
    environment:
      POSTGRES_DB: security_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    networks:
      - security

  minio:
    container_name: minio-service
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    environment:
      MINIO_URL: http://127.0.0.1
      MINIO_PORT: 9000
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    depends_on:
      - postgres
    volumes:
      - ./docker_volumes/minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - security

networks:
  security:
    driver: bridge

