server:
  port: ${APP_PORT:8089}
  servlet:
    context-path: "/security"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security_db
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  minio:
    url: ${S3_URL:http://127.0.0.1:9000}
    bucketMap:
      test:
        name: ${BUCKET_NAME:test}
        access: ${BUCKET_ACCESS:user}
        secret: ${BUCKET_SECRET:password}

myapp:
  api:
    base-url: api/v1